"""add_correlation_id

Revision ID: 5ebfad028703
Revises: 27216f98c015
Create Date: 2026-08-24 00:14:41.846035
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebfad028703'
down_revision: Union[str, None] = '27216f98c015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('correlation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_processing_jobs_correlation_id'), 'processing_jobs', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_correlation_id'), table_name='processing_jobs')
    op.drop_column('processing_jobs', 'correlation_id')
    # ### end Alembic commands ###
