"""Add extractor_type

Revision ID: 7e17279d29e6
Revises: 5ebfad028703
Create Date: 2026-08-25 16:23:53.268000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e17279d29e6'
down_revision: Union[str, None] = '5ebfad028703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_fields', sa.Column('normalized_value', sa.String(), nullable=True))
    op.add_column('extracted_fields', sa.Column('validation_state', sa.String(), nullable=True))
    op.add_column('extracted_fields', sa.Column('validation_messages', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('extracted_fields', sa.Column('confidence_category', sa.String(), nullable=True))
    op.add_column('extracted_fields', sa.Column('validation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extractions', sa.Column('extractor_type', sa.String(), server_default='rule_based', nullable=False))
    op.add_column('extractions', sa.Column('fallback_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extractions', sa.Column('overall_confidence', sa.Float(), nullable=True))
    op.add_column('extractions', sa.Column('validation_status', sa.String(), nullable=True))
    op.add_column('extractions', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('extractions', sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('extractions', 'model_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('extractions', 'prompt_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extractions', 'prompt_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('extractions', 'model_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('extractions', 'validation_summary')
    op.drop_column('extractions', 'decision')
    op.drop_column('extractions', 'validation_status')
    op.drop_column('extractions', 'overall_confidence')
    op.drop_column('extractions', 'fallback_metadata')
    op.drop_column('extractions', 'extractor_type')
    op.drop_column('extracted_fields', 'validation_metadata')
    op.drop_column('extracted_fields', 'confidence_category')
    op.drop_column('extracted_fields', 'validation_messages')
    op.drop_column('extracted_fields', 'validation_state')
    op.drop_column('extracted_fields', 'normalized_value')
    # ### end Alembic commands ###
